version: '3'

networks:
  lottery:
    external: true

services:

  lottery:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: 'mysql'
      MYSQL_PORT: '3306'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_DB_NAME: 'lottery_db'
    volumes:
      - lottery:/usr/app
    networks:
      - lottery
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lottery_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    command:
      [
        mysqld,
        --default-authentication-plugin=mysql_native_password,
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_unicode_ci,
        --bind-address=0.0.0.0,
      ]

    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - lottery

volumes:
  db-data:
  lottery: